import { Router } from "express";
import user from "./user.routes";
import questao from "./questao.routes";
import hardskill from "./hardskill.routes";
import alunoHardskills from "./aluno_hardskill.routes";
import aluno from "./aluno.routes";
import atividadeAvaliativa from "./atividadeAvaliativa.routes";
import avaliacao360 from "./avaliacao360.routes";
import curso from "./curso.routes";
import disciplina from "./disciplina.routes";
import grupo from "./grupo.routes";
import professor from "./professor.routes";
import questaoDia from "./questaoDia.routes";
import softskill from "./softskill.routes";
import tarefa from "./tarefa.routes";
import turma from "./turma.routes";
import alunoGrupo from "./aluno_grupo.routes";
import alunoSoftskill from "./aluno_softskill.routes";
import alunoTurma from "./aluno_turma.routes";
import atividadeAvaliativaHardskill from "./atividadeAvaliativa_hardskill.routes";
import avaliacao360Softskill from "./avaliacao360_softskill.routes";
import disciplinaHardskill from "./disciplina_hardskill.routes";
import professorDisciplina from "./professor_disciplina.routes";
import professorTurma from "./professor_turma.routes";
import cursoTurma from "./curso_turma.routes";
import turmaHardskill from "./turma_hardskill.routes";

const router = Router();
router.use("/usuario", user);
router.use("/questao", questao);
router.use("/hardskill", hardskill);
router.use("/aluno", aluno);
router.use("/atividade_avaliativa", atividadeAvaliativa);
router.use("/avaliacao360", avaliacao360);
router.use("/curso", curso);
router.use("/disciplina", disciplina);
router.use("/grupo", grupo);
router.use("/professor", professor);
router.use("/questaoDia", questaoDia);
router.use("/softskill", softskill);
router.use("/tarefa", tarefa);
router.use("/turma", turma);

// N-N
router.use("/aluno_hardskills", alunoHardskills);
router.use("/aluno_grupo", alunoGrupo);
router.use("/aluno_softskill", alunoSoftskill);
router.use("/aluno_turma", alunoTurma);
router.use("/atividade_avaliativa_hardskill", atividadeAvaliativaHardskill);
router.use("/avaliacao360_softskill", avaliacao360Softskill);
router.use("/disciplina_hardskill", disciplinaHardskill);
router.use("/professor_disciplina", professorDisciplina);
router.use("/professor_turma", professorTurma);
router.use("/curso_turma", cursoTurma);
router.use("/turma_hardskill", turmaHardskill);

export default router;
